# Generated by Django 4.2.3 on 2023-07-15 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
